### ISSUE TITLE
inputs argument needed

### ISSUE THREAD

**Issue by obook** [namgk/node-red-contrib-pythonshell#1]
Hello, first tank you very much for your node, it run great on Node-RED v0.16.2 / Ubuntu 16.04/Python3
As I have projects for you need, is it possible to have the possibility to push parameters/arguments to your node ? also, change the node's name ?
Regards,
OB.

**Comment by namgk** [comment]
Why do you need to change the node name? Adding parameters would be easy and is on my plan. I'm just not ready for that, if you have any pull request that'd be very welcome. 

Thanks

**Comment by obook** [comment]
Cool, thank you. About name is just have a 'Name' field for labeling.

**Comment by abranco21** [comment]
Hi, thanks for the node.
I need send 2 var u and k from multimeter.py file to pythonshell node-red, can you show one example, pls.
Python 3, Raspbian.
Thanks.

**Comment by namgk** [comment]
@abranco21 have no idea what you're talking about, what is multimeter.py? I've updated the code to fix this issue and show an example flow.

Thanks

**Comment by abranco21** [comment]
Hi Nicolas,
I 've this simple code in python 3 and I need send to pythonshell nodered all data (k, 100, u, 230).
k = 100,
u = 230
print ('k = ' , k)
print ('u = ' , u)
Can you show me one example, pls.
Python 3, Raspbian.
Thanks.
