### ISSUE TITLE
Adding envionment path and find error -4508

### ISSUE THREAD

**Issue by teewitmilk** [namgk/node-red-contrib-pythonshell#20]
Hi ,
I'm pretty new to nodered and I've been trying to use the python-shell node but no luck. I did activate the virtual environment in cmd ,and filled path of the script and the environment path on the python shell node. Still it keeps showing error -4058. Anyway to solve this issue?

Thanks
Wit

**Comment by namgk** [comment]
What does the path look like?

**Comment by teewitmilk** [comment]
Hi namgk,
The path look like this:
![image](https://user-images.githubusercontent.com/38879688/103163521-6466fb00-4831-11eb-9a4f-766930831dad.png)

and this is what I have run on my cmd:
![image](https://user-images.githubusercontent.com/38879688/103163537-89f40480-4831-11eb-9dcb-123c8481dc03.png)
