### ISSUE TITLE
Python 3 / choose python interpreter

### ISSUE THREAD

**Issue by Dannsei** [namgk/node-red-contrib-pythonshell#6]
Feature request: it would be nice to have easy way within Node Red to select the Python interpreter to be used.  At the moment this goes by default to Python 2.7 rather than Python 3.5.

The manual way to do this is by changing line 18 of PythonshellNode.js  to replace 'python' with python3.5 (or python3) i.e. change:

` var py = this.spawn('python', [this.pyfile, msg]);`

to:

` var py = this.spawn('python3.5', [this.pyfile, msg]);`

**Comment by hans-peter123** [comment]
Sorry, but how to use python3 wir the version 1.1.1? 
Because a few things are changed.
Thank you for your help!

**Comment by hans-peter123** [comment]
Sorry, I found it by myself: In src/PythonShellNode.js in line 49:
`var spawnCmd = (this.virtualenv ? this.virtualenv + '/bin/' : '') + 'python'`
to
`var spawnCmd = (this.virtualenv ? this.virtualenv + '/bin/' : '') + 'python3'`

Thanks!

**Comment by namgk** [comment]
glad you found it. I might incorporate this in a future release. Thanks
